### PR TITLE
Fix FindCommandTest.java test cases

### LINKED ISSUE #98: Modify FindCommand test cases

### PR DESCRIPTION
**Pull request by ojunyi**
Closes #98 

Re-enable the test cases for FindCommand that were previously commented out.

### CODE REVIEW

File: src/test/java/seedu/coursepilot/logic/commands/FindCommandTest.java [hunk 1]
```diff
@@ -60,29 +56,40 @@ public void equals() {
         assertFalse(findFirstCommand.equals(findSecondCommand));
     }
 
-    /*
+    @Test
```
Comment (gaoze24) [inline src/test/java/seedu/coursepilot/logic/commands/FindCommandTest.java]: Well considered test case

**Review by tehmiw — COMMENTED** [review]
great
